name: Aggiorna calendario

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev libssl-dev libxml2-dev \
            libmagick++-dev imagemagick \
            libharfbuzz-dev libfribidi-dev libfreetype6-dev libcairo2-dev  # Required for ragg

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install additional dependencies
        run: |
          Rscript -e 'install.packages(c("officer", "ragg"))'

      - name: Install main dependencies
        run: |
          Rscript -e 'install.packages(c("tidyr", "dplyr", "lubridate", "glue", "stringr", "httr", "jsonlite", "flextable", "calendar", "DescTools", "rmarkdown", "knitr", "kableExtra", "curl", "magick"))'

      - name: Run R script
        env:
          GCAL_FAMIGLIA: ${{ secrets.GCAL_FAMIGLIA }}
          ID_INDIRIZZO: ${{ secrets.ID_INDIRIZZO }}
          ID_CIVICO: ${{ secrets.ID_CIVICO }}
        run: |
          Rscript lifeR_master.R
