name: Aggiorna calendario

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev libssl-dev libxml2-dev \
            libmagick++-dev imagemagick \
            libharfbuzz-dev libfribidi-dev libfreetype6-dev libcairo2-dev  # Required for ragg

      - name: Set up Italian locale
        run: |
          sudo locale-gen it_IT.UTF-8
          sudo update-locale LANG=it_IT.UTF-8
          export LANG=it_IT.UTF-8
          export LC_ALL=it_IT.UTF-8
          
      - name: Install Pandoc
        run: |
          sudo apt-get install -y pandoc


      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install additional dependencies
        run: |
          Rscript -e 'install.packages(c("officer", "ragg"))'

      - name: Install main dependencies
        run: |
          Rscript -e 'install.packages(c("tidyr", "dplyr", "lubridate", "glue", "stringr", "httr", "jsonlite", "flextable", "calendar", "DescTools", "rmarkdown", "knitr", "kableExtra", "curl", "rsvg", "magick"))'

      - name: Set Time Zone
        run: echo "TZ=Europe/Rome" >> $GITHUB_ENV

      - name: Run R script
        env:
          GCAL_FAMIGLIA: ${{ secrets.GCAL_FAMIGLIA }}
          ID_INDIRIZZO: ${{ secrets.ID_INDIRIZZO }}
          ID_CIVICO: ${{ secrets.ID_CIVICO }}
          LANG: it_IT.UTF-8
          LC_ALL: it_IT.UTF-8
        run: |
          Rscript lifeR_master.R

      - name: Commit and push updated index.html
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Auto-update index.html [skip ci]" || echo "No changes to commit"
          git push
